# Generated by Django 5.1.5 on 2025-02-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='despcription',
            new_name='description',
        ),
    ]
